### ISSUE TITLE
Syntax error, sftpclone.py", line 718

### ISSUE THREAD

**Issue by galileo-pkm** [unbit/sftpclone#19]
Hi
I'm getting a syntax error with python 2.6:

[root@vm0 backup_server]# sftpclone -h
Traceback (most recent call last):
  File "/usr/bin/sftpclone", line 4, in <module>
    from sftpclone.sftpclone import main as sftpclone
  File "/usr/lib/python2.6/site-packages/sftpclone/sftpclone.py", line 718
    args_mapping['k']: v

I believe this is due to syntax difference between new python versions and 2.6.
Already "fixed" one instance related to "dict comprehension" on line 93 but I'm stuck with this one.
I (obviously) have very limited knowledge of python so if someone can help me here ...

Thanks

**Comment by aldur** [comment]
Thanks for reporting the issue.

Please note that `sftpclone` doesn't officially support Python 2.6 (the last core supported release is dated November 2013). Anyway, the problems you highlighted are easy to fix and are related, indeed, to dictionary comprehension and set literals.

A patch is [here](https://github.com/unbit/sftpclone/files/140287/Python_2.6_support.txt) and pasted below. I didn't tested it thoroughly, but it fixes the errors. If the other libraries we use are fine as well (Paramiko, specifically), you should be good to go.

You can apply it, from within the repository directory, by using the following command:

```bash
$ git apply Python_2.6_support.txt
```  

Paste of the patch:
```diff
diff --git a/sftpclone/sftpclone.py b/sftpclone/sftpclone.py
index f6d5892..ee9af0d 100644
--- a/sftpclone/sftpclone.py
+++ b/sftpclone/sftpclone.py
@@ -88,11 +88,11 @@ class SFTPClone(object):
                 ]
 
                 # actually, is a set of excluded files
-                self.exclude_list = {
+                self.exclude_list = set(
                     g
                     for pattern in exclude_list
                     for g in glob.glob(path_join(self.local_path, pattern))
-                }
+                )
         else:
             self.exclude_list = set()
 
@@ -716,17 +716,17 @@ def main(args=None):
         "key": "identity_files",
     }
 
-    kwargs = {  # convert the argument names to class constructor parameters
-        args_mapping[k]: v
+    kwargs = dict(  # convert the argument names to class constructor parameters
+        (args_mapping[k], v)
         for k, v in args.items()
         if v and k in args_mapping
-    }
+    )
 
-    kwargs.update({
-        k: v
+    kwargs.update(dict(
+        (k, v)
         for k, v in args.items()
         if v and k not in args_mapping
-    })
+    ))
 
     # Special case: disable known_hosts check
     if args['disable_known_hosts']:
```

**Comment by galileo-pkm** [comment]
Thanks for your reply, this patch fixed those issues.
Some of the python modules are missing from my install so if a manage to fix those 
I will reply back. 

Thanks

**Comment by aldur** [comment]
I'm closing this due to inactivity. Fell free to reopen it anytime :)
